### ISSUE TITLE
Should be a view page for coupon details

### ISSUE THREAD

**Issue by arpitash** [QueppelinTech/FoxHopr#1]
a. Open FoxHopr Admin URL
 b. Enter credentials for authentication. 
c. Enter credentials for admin Login
 d.Go to Coupon Code
 e. Edit the mail id given.
 f. Send the mail to that editted mail. 

![03-01-2017-03-49-48](https://cloud.githubusercontent.com/assets/24872709/21604989/5182ed76-d1cc-11e6-88cc-03d4533e3161.png)

**Comment by arpitash** [comment]
Bug has been retested and closed

**Comment by merubh** [comment]
Bug has been successfully been tested and closed.
