### ISSUE TITLE
Design issues for Actions column in User List. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#12]
Following are the design issues visible at actions: 
a. The Buttons are not responsive i.e there alignment is improper when enlarging of page. 
b. The Label on both the icon is showing as view which should not be the case. 
Please find the screenshot for the same: 
![fh_bt_11](https://cloud.githubusercontent.com/assets/24872612/22538624/d3839544-e939-11e6-9ae0-7d1a414e46f5.png)

**Comment by aakashquepp** [comment]
fixed

**Comment by merubh** [comment]
Bug has been successfully been tested and closed.
