### ISSUE TITLE
Database error occurs when clicking on removal request at admin panel.

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#2]
a. Open FoxHopr Admin URL                                                                                                             
b. Enter credentials for authentication 
c. Enter credentials for admin Login 
d. Select Business Owners.                                                                    
e. Click on removal request.                                                   
![fh_bt_01](https://cloud.githubusercontent.com/assets/24872612/22455227/26bbdb48-e7b1-11e6-8067-313ed022864e.png)

**Comment by saurabhjai** [comment]
Bug has been fixed

**Comment by merubh** [comment]
Same issue is visible for view user and group change request.

**Comment by merubh** [comment]
"sorry the page you are looking for does not exist" error is displayed now.

**Comment by merubh** [comment]
Bug has been tested and closed.
