### ISSUE TITLE
Country Should  be before State & City in user signup page. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#21]
Country Should  be before State & City in user signup page. Please refer to the screenshots. 
![fh_bt_20](https://cloud.githubusercontent.com/assets/24872612/22641636/8c0833c2-ec7d-11e6-9960-0ad7c7041c11.png)

**Comment by aakashquepp** [comment]
fixed.

**Comment by merubh** [comment]
https://beehopr.com/new_demo/businessOwners/profile/edit. Request you to correct here.

**Comment by merubh** [comment]
Bug has been tested and closed.
