### ISSUE TITLE
My Profile tab for member at front user is not working. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#22]
My Profile tab for member at front user is not working. 
![fh_bt_21](https://cloud.githubusercontent.com/assets/24872612/22641742/f90f84ca-ec7d-11e6-908a-9b7ef7e8d26a.png)

**Comment by saurabhjai** [comment]
Bug fixed. Please check and confirm

**Comment by merubh** [comment]
Bug has been retested and closed.
