### ISSUE TITLE
View details for users in business owners are not working. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#23]
View details for users in business owners are not working.  Please refer to the screenshots: 
![fh_bt_22](https://cloud.githubusercontent.com/assets/24872612/22644746/bde5148a-ec89-11e6-8495-10d384de0399.png)

**Comment by saurabhjai** [comment]
Bug fixed. PLease check

**Comment by merubh** [comment]
Bug has been successfully tested and closed in new_demo environment.
