### ISSUE TITLE
While clicking on review requests, review report tabs get automatically opened. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#26]
While clicking on review requests, review report tabs get automatically opened.  
![fh_bt_25](https://cloud.githubusercontent.com/assets/24872612/22645685/41596d62-ec8e-11e6-9be4-f538ab0cfa21.png)

**Comment by saurabhjai** [comment]
Bug Fixed. Please check now

**Comment by merubh** [comment]
Bug has been successfully tested and closed.
