### ISSUE TITLE
All the rejected/deleted reviews are not displayed in review reports. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#28]
All the rejected/deleted reviews are not displayed in review reports. Only the ones with status "Pending" or "Approved" status is displayed. QA team suggests that Rejected reviews should also be displayed. 
Please refer to the screenshot below: 
![fh_bt_27](https://cloud.githubusercontent.com/assets/24872612/22646053/5e516120-ec90-11e6-9fee-b63eda92efed.png)

**Comment by jbander** [comment]
You guys built in this feature. Please do the needful. Yes, we should be able to always view all reviews, of all status. It is important to be able to view rejected.

**Comment by merubh** [comment]
Bug has been successfully been tested and closed.
