### ISSUE TITLE
Download Excel Sheet button should be present for review report. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#30]
Download Excel Sheet button should be present for review report.  PFA for the same: 
![fh_bt_29](https://cloud.githubusercontent.com/assets/24872612/22680754/b677f3b0-ed2f-11e6-8a02-9deab3702018.png)

**Comment by saurabhjai** [comment]
Added this feature.

**Comment by merubh** [comment]
Download feature is added hence closing the bug.
