### ISSUE TITLE
Send button should be included in action column for the mail template.

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#31]
Send button should be included in action column for the mail template. Plesae refer to the screenshot attached below:
![fh_bt_30](https://cloud.githubusercontent.com/assets/24872612/22680945/cb069a06-ed30-11e6-9f4b-26210be03e4d.png)

**Comment by saurabhjai** [comment]
Send test mail button is added. Please check

**Comment by merubh** [comment]
Bug has been successfully tested and closed.
