### ISSUE TITLE
New multimedia file for FAQ, Videos(Training video and webcast) and PDF .

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#32]
As discussed in the call, New multimedia files for FAQ, Videos(Training video and webcast) and PDF need to be provided having BeeHopr Logo. Request you to do the needful.

**Comment by jbander** [comment]
Please post to basecamp. Video and PDFs will be provided asap. We are reviewing now to approve final versions.

**Comment by merubh** [comment]
Would be moving forward with discussion in basecamp.
