### ISSUE TITLE
No Alert message after filling of feedback form. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#34]
No Alert message after filling of feedback form.  Please find the screenshot for the same: 

![fh_bt_32a](https://cloud.githubusercontent.com/assets/24872612/22734851/2dbb53e8-ee1d-11e6-8f35-5c3be7e18d5d.png)

**Comment by jbander** [comment]
There is suppose to be a thank you message at top that disappears after some time.

**Comment by merubh** [comment]
Still no alert message has been received . Request you to do the needful.

**Comment by merubh** [comment]
Bug has been successfully tested and closed.
