### ISSUE TITLE
A member can send infinite number of request review email to the contact. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#36]
A member can send infinite number of request review email to the contact. Instead error message should be displayed "Mail has already send to the contact. Kindly wait for 10 days to send the mail again".
Please refer to the screenshot for the same: 
![fh_bt_34](https://cloud.githubusercontent.com/assets/24872612/22736122/bb202f6a-ee22-11e6-98da-16c41e3c5c60.png)

**Comment by jbander** [comment]
It is ok for member to send infinite review requests to the client. Can client review the member multiple times? That should be limited to one.

**Comment by merubh** [comment]
Client can review the member just once. Issue was with infinite reviews which is okay from your side. hence we are marking it as "Not A Bug" and closing it.
