### ISSUE TITLE
Both custom dates and select duration drop down have the same time frame.  

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#39]
Both custom dates and select duration drop down have the same time frame.  Please find the screenshot for the same. Only on of the either dropdown should come: 
![fh_bt_37a](https://cloud.githubusercontent.com/assets/24872612/22882382/d077d06a-f210-11e6-94b6-38213011c7b1.png)

**Comment by aakashquepp** [comment]
fixed

**Comment by merubh** [comment]
Part of the functionality hence not a bug. Closing the issue.
