### ISSUE TITLE
Group column is not required for cancelled user. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#41]
Group column is not required for cancelled user as the for an already cancelled user it would show group name as "Group" for all the entries. Please find the screenshot below for the same: 
![fh_bt_39a](https://cloud.githubusercontent.com/assets/24872612/22883445/51f7d4dc-f216-11e6-8f03-1f186d2e2ac0.png)

**Comment by saurabhjai** [comment]
Bug fixed

**Comment by merubh** [comment]
Bug has been tested and closed.
