### ISSUE TITLE
Mail Template should have a send option to send test mail in the action column. 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#5]
Mail Template should have a send option to send test mail. It ensure that a proper mail is flowing to the end user. 

Please find the screenshot of the same below: 
![fh_bt_04](https://cloud.githubusercontent.com/assets/24872612/22508183/d6986524-e8ae-11e6-8ec3-535faaa5728f.png)

**Comment by saurabhjai** [comment]
Done

**Comment by merubh** [comment]
Bug has been tested and resolved.
