### ISSUE TITLE
Status should be given as active/de-active in Mail Templates

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#6]
Status should be given as active/de-active in Mail Templates as per discussion with Jon/Tamara so as to know which email are coded at back end and which are not.  Please find the screenshot for the same. 
![fh_bt_05](https://cloud.githubusercontent.com/assets/24872612/22537878/38b67b3a-e934-11e6-9b1f-458e3de271dd.png)

**Comment by saurabhjai** [comment]
Status added. Please check

**Comment by merubh** [comment]
Bug has been successfully tested and closed.
