### ISSUE TITLE
Download button for Status report page is not working correctly.

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#93]
Download button for Status report page is not working correctly. Please find the screenshot fort the same. 
![fh_bt_85a](https://cloud.githubusercontent.com/assets/24872612/24399056/20679306-13c9-11e7-9117-e5e2a8c4c514.png)
![fh_bt_85b](https://cloud.githubusercontent.com/assets/24872612/24399057/20749718-13c9-11e7-997d-53ded020422f.png)

**Comment by aakashquepp** [comment]
fixed..

**Comment by merubh** [comment]
Bug has been successfully tested and closed.
